// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AddTodo: typeof import('./components/AddTodo.vue')['default']
    CarbonClose: typeof import('~icons/carbon/close')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonTrashCan: typeof import('~icons/carbon/trash-can')['default']
    CompletedTasks: typeof import('./components/CompletedTasks.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    README: typeof import('./components/README.md')['default']
    ToDoItem: typeof import('./components/ToDoItem.vue')['default']
  }
}

export { }
